pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = '32f08b30-b602-4f85-932a-3cb498ad7d7d'
        DOCKER_IMAGE = 'pedrohgil/springbootapp'
        DOCKER_TAG = "${env.BUILD_ID}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out the code...'
                git url: 'https://github.com/PedroHGill/devops-23-24-JPE-1231851.git'
            }
        }

        stage('Set Permissions') {
            steps {
                dir('CA2/part2/') {
                    echo 'Setting executable permissions on gradlew...'
                    bat 'gradlew.bat'
                }
            }
        }

        stage('Assemble') {
            steps {
                dir('CA2/part2/') {
                    echo 'Assembling the application...'
                    bat './gradlew assemble'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CA2/part2/') {
                    echo 'Running unit tests...'
                    bat './gradlew test'
                }
            }
        }

        stage('Javadoc') {
            steps {
                dir('CA2/part2/') {
                    echo 'Generating Javadoc...'
                    bat './gradlew javadoc'
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: 'build/docs/javadoc',
                        reportFiles: 'index.html',
                        reportName: 'Javadoc'
                    ])
                }
            }
        }

        stage('Archive') {
            steps {
                dir('CA2/part2/') {
                    echo 'Archiving artifacts...'
                    archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
                }
            }
        }

        stage('Create Dockerfile') {
            steps {
                dir('CA2/part2/') {
                    script {
                        def dockerfileContent = """
                        FROM tomcat:10
                        RUN apt-get update && apt-get install -y dos2unix
                        WORKDIR /app
                        COPY . .
                        EXPOSE 8080
                        RUN dos2unix ./gradlew
                        ENTRYPOINT ["./gradlew"]
                        CMD ["bootRun"]
                        """
                        writeFile file: 'Dockerfile', text: dockerfileContent
                    }
                }
            }
        }

        stage('Publish Image') {
            steps {
                script {
                    echo 'Building and publishing Docker image...'
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        dir('CA2/part2/') {
                            def customImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                            customImage.push('latest')
                        }
                    }
                }
            }
        }
    }
}