version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - h2-data:/app/db-backup

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  h2-data:
    driver: local