# Use the official Gradle image to build the application
FROM tomcat
RUN apt-get update && apt-get install -y dos2unix
WORKDIR /app

# Copy the project files to the container
COPY . .

# Expose the application port
EXPOSE 8080

RUN dos2unix ./gradlew

# Run the Spring Boot application
ENTRYPOINT ["./gradlew"]
CMD ["bootRun"]
